### ISSUE TITLE
Data files missing after install.

### ISSUE THREAD

**Issue by 1uc** [ryanvarley/ExoData#11]
Nice tool, really like the ideas behind it :)

After installing I get this error

    FileNotFoundError: [Errno 2] No such file or directory: '/home/lucg/.local/lib/python3.4/site-packages/exodata-2.0-py3.4.egg/exodata/data/magnitude_estimation.dat'

I tried to fix this. See pull request :)

Cheers and thanks for the cool tool

**Comment by ryanvarley** [comment]
Great, thanks.
