### ISSUE TITLE
Error in planet temperature estimate

### ISSUE THREAD

**Issue by epascale** [ryanvarley/ExoData#14]
in equations.py, lines 173-174 read
if T_p is None:
            T_p = T_s \* ((1-A)/epsilon)*_(1/4) \* sqrt(R_s/(2_a))

the factor 1/4 evaluates to 0 rather than 0.25

**Comment by ryanvarley** [comment]
Hey, the file begins with `from __future__ import division` and so it should equal 0.25. Was this evaluating incorrectly?
