### ISSUE TITLE
Check for type of parent

### ISSUE THREAD

**Issue by JVSeidel** [ryanvarley/ExoData#21]
Hi Ryan,

I am currently trying to sort the database and need to get only planets that transit around stars of a certain magnitude.

Unfortunately that also gives me planets that don't have a star as parent or no parent at all, meaning that I can't sort for the planets for planet.star.magV. And I get a astroclasses.HierarchyError "Object has no Star as a parent object"

Any suggestions on how to check if a parent exists and if said parent is a star?

Many thanks,

Julia

**Comment by JVSeidel** [comment]
if isinstance(planet.parent, exodata.astroclasses.Star):

This is the solution. Would be great if that could be implemented as a check for users.

**Comment by ryanvarley** [comment]
Hey, i dont maintain this package anymore. Happy to have new maintainers on board though. I'll add something to the readme.
